<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-IMPERIUS" failures="2" tests="12" name="Test" time="9.307" errors="0" timestamp="2024-06-19T11:08:35 CEST">
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionBrokenlinks" time="0.046">
    <skipped/>
  </testcase> <!-- AdmissionBrokenlinks -->
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.014"/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.002"/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.013"/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.002"/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.003"/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.001"/>
  <testcase classname="Real_Project.First_Real_Program" name="Counter" time="0.004"/>
  <testcase classname="Real_Project.First_Real_Program" name="Counter" time="0.004"/>
  <testcase classname="Real_Project.First_Real_Program" name="verifyLogo" time="0.134">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Real_Project.First_Real_Program.verifyLogo(First_Real_Program.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogo -->
  <testcase classname="Real_Project.First_Real_Program" name="verifyTitle" time="0.028"/>
  <testcase classname="Real_Project.Program_2" name="AdmissionLogin" time="0.0">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false],
	expected [true] but found [false],
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]
at Real_Project.Program_2.AdmissionLogin(Program_2.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- AdmissionLogin -->
</testsuite> <!-- Test -->
